### PR TITLE
Update as-3d-cnt.rq

### PR DESCRIPTION
**Pull request by andreasbueckle**

### CODE REVIEW

**Comment by andreasbueckle** [comment]
Updated query to point to from HRA release notes 2.0.

**Comment by bherr2** [comment]
That is an old query that doesn't work with HRA v2.0 / CCF v2.3.0

**Comment by andreasbueckle** [comment]
OK, can you add a query that shows the number of
- 3D AS 
- 2 United files
- 65 organs themselves

for HRA2.0?

**Comment by bherr2** [comment]
Yeah, I'll do that. was just starting to do that when I saw the PR come up.

**Comment by andreasbueckle** [comment]
Thank you!

**Comment by bherr2** [comment]
Added new queries to support this here: https://github.com/hubmapconsortium/ccf-grlc/commit/a198aad3187944a6babb679807ec245423bfc0b6

**Pull request closed without merging**
